### ISSUE TITLE
Week 3 day 2 - Planning Tic Tac Toe - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#10]
# Tic tac toe

With a partner,I want you to create a design for a tic tac toe game. Do not worry about writing code for the first level. I really want you to practice your technical design skills here and think about how you would code this. 

### Explorer Mode

- [x] Submit a full design of how to approach this problem. This should include: 
  - a mock up (could be a picture of drawing) 
  - implementation details, such as how you are implementing each square
  - a list of events that you are listening to. 
  - this should contain psuedo-code on how you are handling each event, and all game logic
- Your design should take into account all requirements for adventure mode 
### Adventure Mode

- [ ] As a user I should be able to see a tic tac toe board
- [ ] as a user, the game should alternate turns
- [ ] As a user, i should be able to click in a square and play either `X` or `O` depending on whose turn it is
- [ ] As a user, when I get three in a row, I should be told i won and the game should be over 
- [ ] Create a `vs computer` mode, that picks a random square
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice) 
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [ ] Using a Min-max tree, make your computer AI unbeatable

## Turning In

Your planning should be on a Trello board. To turn in, add me to the Trello board, and also drop me a link on this issue.

**Comment by floh1695** [comment]
https://trello.com/b/ANZ7iB86/tic-tac-toe

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/EuZzVSYPds1yM/200w_d.gif)
