### ISSUE TITLE
Week 3 Day 4 - Hackathon - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#12]
# Hackathon!

Your homework this weekend is the Hack-a-thon. Good Luck! I am here if you have any questions. 

### Turning in
To turn this in, on Sunday, submit to me the github repo that you are working on.

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/l378A0z8HJHCKDEWI/200w_d.gif)

**Comment by floh1695** [comment]
https://github.com/floh1695/directory-bot
