### ISSUE TITLE
Week 5 Day 1 Welcome to C# - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#17]
# Intro to Types & Re-Focusing

Welcome to C#! The first thing you must practice is mastering what types are and how they affect your code. 

* For this homework you can not use `var` *

### Setup

- open `Visual Studio 2017` and create a new `console application` 
- be sure to select `create git repo` and make sure it has a `.gitignore`

### Explorer Mode

- [x] Create the following vairbles. Use the type you think would be the best
 - number of dogs running around a dog park
 - the number of sandwhiches You can eat when you are hungry
 - the amount of money it costs to buy a nice dinner 
 - what color your dream car is
 - what make your dream car is
 - what model your dream is
 - todays date
 - the first letter of you name
 - the number of stars in the sky

 - [x] Print out each variable in the middle of string describing the variable. 
  ex: for the number of dogs in the park, I want you to print out ` There are 5 dogs running around the park` 

  - [ ] We have tackled JavaScript and are about to tackle our 4th language. You have grown as a developer and a person in the last 4 weeks. Create for me a blog post on medium on 1 of the following prompts

   - Pick 1 topic technically that we have learned and create a blog post explaining it to a new developer
   - Blog about a struggle that you have encountered and overcome during your tenure here so far. 
   - Pick a new techonlogy that we haven't hit yet (or won't) and create a intro blog for that. 

### Adventure Mode

- [ ] Work more on Geopardy some more

### Epic Mode

- [ ] Explore C# some more by creating a simple number guessing game. 

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are

These steps will be followed for almost every assignment going forward. Once you've completed at least _explorer_ mode and you're satisfied with your work, let's get it published. First let's get it up on GitHub.

- First, let's add all our work to git, and ask it to commit it:

  ```sh
  git add .
  git commit -m "My first webpage"
  ```

  Feel free to replace _"My first webpage"_ with a more meaningful message.

- Push our local commits to GitHub:

  ```sh
  git push -u origin master
  ```

  The `-u` option tells git we want to making pushing the `master` branch to `origin` the default, so next time, we can just type `git push`.

Once you are completely, go to the issue on our `assignments` repository, leave the link the repo of your work, and close the issue. I will not know you are down until you close the issue. 

## Additional Resources

**Comment by floh1695** [comment]
https://github.com/floh1695/helloCS

Blog post is left

**Comment by floh1695** [comment]
https://medium.com/@https://medium.com/@charlesbayley/introduction-to-object-oriented-interfaces-90d055acb64ccharlesbayley/introduction-to-object-oriented-interfaces-90d055acb64c

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/GKWxzNiatzVaU/200w_d.gif)
