### ISSUE TITLE
Week 7 Day 3 - Movie API - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#26]
# Lets All Go to the Movies...

You are tasked with taking the Movie DB you created and putting that into an API. This API should use the simple Movie Database that we created when we started Entity Framework. 

## Objectives
- Practice Creating Simple APIs
- Practice working with API Tools, such as POSTMAN (https://www.getpostman.com/)

### Explorer Mode
- [x] Create the DBContext, Models, and Controllers in their own folders
- [x] Create `GET /Movies` Endpoint that returns all movies
- [x] Create `GET /Search?title=Jurassic` that returns all movies where the title contains the title parameter
- [x] Create a `POST /Movie` endpoints that adds a movie to the database. THis should take a JSON body
- [x] Create a `GET /Movies?genre={Genre}` that returns movies of only that Genre

 
### Adventure Mode
- [ ] Normalize your database to have `Genre` be its own table
- [ ] Create the endpoints that allows to Update Movies
- [x] Extend your `Search` endpoint to have many 
 

### Epic Mode
- [ ] Create an angular app that talks to your API and Interacts with all the endpoints

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are complete with your assignmnet, link the new repo here.

**Comment by floh1695** [comment]
https://github.com/floh1695/MovieAPI

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/l378x9bADTsX8lXO0/200w_d.gif)
