### ISSUE TITLE
Week 8 Day 1 -  It was the developer, in the library, with angular - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#28]
# It was the developer, in the library, with angular

The library was super impressed with your API, now they want you to create a Web UI for them, using your API. 

## Objectives
- Work on using AngularJS create a UI on top of an API

### Explorer Mode
- [x] Add Angular to your project.
- [x] Implement a Single Page App UI that allows a user to use the endpoints that you created already. This should include
    - [x] Seeing all books
    - [x] Searching for a book to checkout
    - [x] Checking out a book
    - [x] Checking a book back in

*NOTES*
- Create your UI on paper/Whiteboard first, then go to implementation
- Even though you are making a UI, do not get caught up in how it looks, remember to make it functional, then make it working
- If you didn't complete the weekend assignment, work on creating the UI first for the endpoints you have, then work on extending your API
- A user only needs to supply an email to checkout a book, full blown authentication is not needed. 

### Adventure Mode 
*some are extended from the weekend project* 

*catch up*
- [ ] Complete any endpoints you did not from the weekend project 
- [ ] Go back and get caught up on any projects you have outstanding

*styling*
- [ ] Using CSS, style your website to have a modern look

*functionality*
- [ ] Normalize your database to have `Genre` be its own table
- [ ] Create the endpoints that allows to Update Movies
- [ ] Extend your `Search` endpoint to have many 
- [ ] Add users and Authentication

### Epic Mode
*This will challenge your CSS and Design skills*
- [ ] Using `Bootstrap` create a solid UI with no Custom CSS
- [ ] Using `Material Design` as a guideline, learn about and implement a UI that follows the guidelines. 

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are complete with your assignmnet, link the new repo here.

**Comment by floh1695** [comment]
https://github.com/floh1695/Library

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/l4FGIG2uGfzWrqdVu/200w_d.gif)
