### ISSUE TITLE
Week 8 Day 2 - Bootstrap me in Capt'n  - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#29]
# Bootstrap me in Capt'n 

Welcome to `Try It Yourself` (TIY) Sports, the top sport tracking website for people who want to find sports to do try them selves. 

However, before we can get started implementing our features we need to validate our visual design.

Our illustrious designer, B. Strap, has provided us with the following mockups for what the site should look like in both mobile and desktop forms. We also have the original image assets used in the mockup.

Our task is to reproduce this design!

## Desktop view

![desktop view](https://i.imgur.com/gK8Uanp.png)

## Mobile view

![mobile view](https://i.imgur.com/25LDfsz.png)

# Deliverables
- a github url with the all the files need to run the site

# Explorer

- Use [bootstrap](http://getbootstrap.com/docs/3.3/) to reproduce the design
- You do not need to add *any* additional CSS to achieve this design
- Remove all the old content from the index page and place your new HTML there
- Don't worry about making the data dynamic for this level. 
- Do not vary from the design as provided, add nothing, and leave nothing out. Your design doesn't need to be pixel perfect, but with bootstrap it shouldn't be far off.

# Adventure

- Using AngularJS and and API. Create an API that returns hard coded values for the site. Every item that could be dynamic should be represented in this view model

# Epic
 - Create a Database to support this site using EF and  Make the HomePage Actually Dynamic

# Bonus Level

- Keeping the same design feel, add more to the site. What other information could be added and how could we utilize bootstrap components to layout and style those.

**Comment by floh1695** [comment]
https://github.com/floh1695/TiySports

**Comment by mdewey** [comment]
![Awesome Work!](https://media3.giphy.com/media/GvGjMfhlNNWik/200w_d.gif)
