### ISSUE TITLE
Week 8 Day 3 - Enter the Blag-o-sphere - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#30]
# Enter the Blag-o-sphere

For today, we are going to blogging and practicing everything we have talk about. 

## Objectives
- Practice talking like a developer
- Revisit old assignments

## Explorer
- [ ] Blog time. Choose a prompt from the following list
    - Using your own experience as inspiration, create a short list of `survival tricks` for a someone entering a boot camp 
    - Pick 1 topic that we have learned and create a blog post explaining it to a new developer
    - Blog about a struggle that you have encountered and overcame during your tenure here so far. 
    - Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that. 

- [ ] Algorithm Practice -- submit a `gist` of your solution for https://www.codewars.com/kata/form-the-minimum in C# or JavaScript

## Adventure
- [ ] Get caught up on any outstanding homework. 
- [ ] Go back and refactor an old project. 
- [ ] Pick an old AngularJS project that used an API, create an API for that project. Hook up your project to that API
- [ ] Submit a `gist` of the above kata in the other language 

## Epic
- [ ] Further our Hacker News model but creating an API that returns the data for the front page. This includes creating models that produce a valid database. 
- [ ] Create an angular app that consumes and displays the data using Bootstrap to format it.

**Comment by floh1695** [comment]
https://gist.github.com/floh1695/6489d9c9eea8987c0a857e1e7cb2769c

**Comment by floh1695** [comment]
https://medium.com/@charlesbayley/introduction-to-c-operator-overloading-d69912f2c648

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/3ohhwn6TGyOK0abwUE/200w_d.gif)
