### ISSUE TITLE
Week 9 Day 1 - Group News - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#32]
# Extra Extra, Read all about it!

A local news station has contracted your group to build a new idea they have. The have this idea called "citizen journalism". They want a site that allows user to upload their own news story's, and view others peoples news stories. All Articles are posted anomalously,unless the author wants to share their information. 

The site needs these three pages: 

- Dashboard
    - should show the latest 5 stories for each category
        - each stories should show the Headline, and the first 120 characters of the story
        - Each story should link to the stories full page (see below)
    - Should have a link to the Create story page (see below)
    - Should have the news station local and tagline (have fun and get creative, keep it appropriate for work)   

- Create Story Page
    - should allow the user to enter in a new story, 
        - this should have at least
            - headline
            - body (the story)
            - optional author
            - Category
    - Once a story is created, the site should redirect to that story's page

- Story Page
    - this should look like a news article, big headline, and the story body 

The news stories should be stored in a database. 

## Objectives
- Work on using AngularJS create a UI on top of an API
- Creating an API
- Working in Groups on the same project

### Explorer Mode

- [ ] Create the Dashboard page
- [ ] Create the "Create Story" page
- [x] Create the "Story" page

*NOTES*
- Planning and organizing is very important
- Figure out how you are going to be organizing tasks
- Create you UI on paper/Whiteboard first, then go to implementation
- Even though you are making a UI, do not get caught up in how it looks, remember to make it functional, then make it working
- If you didn't complete the weekend assignment, work on creating the UI first for the endpoints you have, then work on extending your API
- A user only needs to supply an email to checkout a book, full blown authentication is not needed. 

### Adventure Mode 
- [ ] Let the user see all stories in a given category 
- [ ] Add a location to each story and have the user be able to see what is happening around them
- [ ] Give your site a slick UI that is mobile friendly

### Epic Mode
- [ ] Add a up/down voting system 

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are complete with your assignmnet, link the new repo here.

**Comment by floh1695** [comment]
https://github.com/tirzahmorrison/SecretForum
We all have been pushing to this repo

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/3o6gEeY0YvFzjtl9MQ/200w_d.gif)
