### ISSUE TITLE
Week 9 Day 2 - Who are you?  - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#33]
# Who are you? 

Today we talked about authentication. Tonight, follow along with this tutorial to learn and understand token based authenication with AngularJS 

# Explorer

- [x] Follow Part 1 and 2 of this tutorial http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/
- [x] Code along with it and submit that as your solution

PROTIP: 
- Do not move onto the next step until the current step works. 
- Ask Plenty of questions. There will be words that are unfamiliar to you

# Adventure

- [x] Round off your group project from last night. 
- [ ] Auth Authentication to your news site. This can be done with your groups or not, your choice.

# Epic
- [ ] Add OAuth to your site news site and allow the users to log in with Google

**Comment by floh1695** [comment]
https://github.com/floh1695/OAuthTutorial
Having trouble testing at part 12

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/cdDwOUeF4XyE0/200w_d.gif)
