### ISSUE TITLE
Week 9 Day 3 _ Contact List - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#34]
# Online Phone Book

You are tasked with building a Web Site that shows a list of contact information of your team to only Authenticated Users

A Contact should have: 
- Name
- Address
- Email
- Phone
- Preferred Contact Method

*NOTE* this will be different from the User Object. 

## Objectives
- Practice using Authentication
- Practice being a Full Stack Developer
- practice working in groups.

## The groups: 
- James and Aaron
- Chris and Wes
- Charlie and Britney
- Kate and Tirzah

## Explorer
- [ ] Create an API that allows a user to sign up
- [ ] Create an API that allows a user to log in
- [ ] Create an API that allows only an Authorized User to see the list of contacts, plus their data
- [ ] Create an angular app that allows the users to access all the routes above
 

## Adventure
- [ ] Add an API that allows a user to create a new contact
- [ ] Update this to be a multi-page SPA app (using angular routing)

## Epic
- [ ] Add an option to share a contact using a unique url 
    - this requires each contact to have their own page

**Comment by floh1695** [comment]
https://github.com/CharlesBayley/OAuthTutorial

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/cdDwOUeF4XyE0/200w_d.gif)
