### ISSUE TITLE
Week 9 Day 4 Presentations - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#35]
# Hello, World!

As a developer, learning is a life long skill that you wil continue to hone. During the last 9 weeks, you have learned many topics, but that is just the tip of the iceberg. For this project I want you to select a topic in technology and give a short presentation about it. 

## Explorer Mode

- [ ] Select a topic, get it approved by your instructor,  and research the topic to understand it
- [ ] Give a 5-10 minutes presentation about that piece of technology that includes: 
    - What is the technology
    - What problem does the technology Solved
    - Why makes the technology unique
- [ ] Include a Hello World Implementation of the app. 
- [ ] Be able to answer some questions about from the group 

*DELIVERABLES:*
- a "Hello World App" demonstrating the technology in a git repo

*NOTES*
- A power point is not needed. As long as you can demo the code and get across the idea of the technology
- 5 mins is not a long time when talking about technology. 

## Adventure
- Build a non-trivial App that uses your technology. For example, if you choose React, a simple Hello, World app displays the current time, but a non-trivial app can talk to the weather API and display the current weather

## Explorer. 
- Keep on Building more and more advance features 

### Topic Ideas
*Not extensive, and not limited to* 

- AWS
- Azure
- Serverless
- GraphQL
- Unity
- Xamarin
- F#
- Typescript
- Chat Bot
- Vue.JS
- React.JS
- Angular
- Ruby
- Python
- Mongo DB
- A Specific HTML5 Feature
- JS Canvas
- Bootstrap 4
- Foundation 
- Webpack
- Raspberry Pi
- Arduino

**Comment by floh1695** [comment]
https://github.com/floh1695/git-presentation

**Comment by mdewey** [comment]
time: 11:06 - 11:20

- Don't assume your audience knows everything
- If things go wrong, don't hang on it, make a joke and then adapt
- take  your time with examples and walk through them 
- The presentation got much better when you started to interact with the audience with the live example

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/3og0IOalrRzSaLLPFe/200w_d.gif)
