### ISSUE TITLE
Week 10 Day 1 -  Blog, The Series Finally - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#36]
# Blog, The Series Finally

We are approaching the final stretch of training and were just exposed to a bunch of new technologies and ideas. Tonight we will be preparing for the final stretch. 

### Explorer Mode

- [x] Clone the PROvision2 repository and get it to build on your laptop 

- [x] Create a blog entry (~5 minute read). Use on the following prompts to get you started
    - Take your presentation and turn it into a blog post
    - Pick a topic of a peer that sparked your interest and create a post about that
    - Share your thoughts about your journey so far and your dreams about looking ahead
    - Pick a technical topic related to something we have covered and created an intro blog for that topic 

- [x] For you homework this week, we are going to be building a Subscription Box site from scratch using all the techniques we have learned so far. For tonight, start creating a rough Database diagram. It will model this site [https://devtrunk.com/collections/all], so you can use this as your references. Remember to keep it simple, and this will only be a rough diagram that might change later. 

- [ ] We will be creating a site together this week in lecture. Create a list of questions of anything we have talked about so we can sure up any ideas you may not be feeling 100% on. This could be anything from CSS, to C#, from UX design to database normalization. 

### Adventure Mode 

- [ ] Solve this problem without using LINQ https://www.hackerrank.com/challenges/big-sorting/problem
- [ ] Go back and get caught up on any outstanding assignments
- [ ] Go back and revisit a hard mode on an old assignment

### Epic Mode
- [x] Start looking at your Grid for your final project. 

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are complete with your assignmnet, link the new repo here.

**Comment by floh1695** [comment]
https://medium.com/@charlesbayley/lets-learn-about-git-branching-4098124a8b0e

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/wjIDrGKbvuGxW/200w_d.gif)
