### ISSUE TITLE
Week 2 Day 2 - Rock Paper Scissors - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#6]
# Rock-Paper-Scissors

Create a simple Rock-Paper-Scissors  game

### Explorer Mode

- [x] As a user I should be able to see three buttons for each player
- [x] as a user, I should be able to pick an option for each player
- [x] As a user,after each player makes their selection, I should be told who won and the game should be over 

### Adventure Mode

- [ ] Create a `vs computer` mode, that picks a selection
- [ ] Modify your `vs computer` mode to follow a specific strategy (your choice) 
- [ ] Make your computer AI unbeatable
- [ ] Give the user a choice to player against the various computer levels or another player
- [ ] Have fun with the CSS by adding colors, animations and effects to make the game more enjoyable

### Epic Mode

- [x] Your game is currently only 1 vs 1, add the ability to add more computer players to the game

## Turning In

Your homework will be assigned to you via `issues` on your `assignments` repository. Once you are

These steps will be followed for almost every assignment going forward. Once you've completed at least _explorer_ mode and you're satisfied with your work, let's get it published. First let's get it up on GitHub.

- First, let's add all our work to git, and ask it to commit it:

  ```sh
  git add .
  git commit -m "My first webpage"
  ```

  Feel free to replace _"My first webpage"_ with a more meaningful message.

- Push our local commits to GitHub:

  ```sh
  git push -u origin master
  ```

  The `-u` option tells git we want to making pushing the `master` branch to `origin` the default, so next time, we can just type `git push`.

- Now that our source code is up on GitHub, let's publish our page to [Surge](https://surge.sh). The command to do this has already been setup for you:

  ```sh
  yarn deploy
  ```

Once you are completely, go to the issue on our `assignments` repository, leave the link the repo of your work, and close the issue. I will not know you are down until you close the issue.

**Comment by floh1695** [comment]
https://github.com/floh1695/rps

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/14ikwT5YXIwjAs/200w_d.gif)
