### ISSUE TITLE
Week 3 Day 1 - Catch your Breathe - 

### ISSUE THREAD

**Issue by mdewey** [floh1695SuncoastDevelopersGuild/assignments#9]
# Catch your Breathe

We have been going a fast pace for the past couple of week. Every so often, you need to reflect on how far you have come.
 
For tonight, we are going to take a little code break and create a blog post. Blog posts are a good way to reflect on what you have done and also share some knowledge. The best way to get better at talking about technology is practice. Blog posts are a way to practice that skill. 

### Explorer Mode

- [x] On medium.com(https://medium.com/), create a blog post that talks about a concept we have went over in class. This could anything  topic from HTML, CSS or JavaScript. Or it could be a lesson that learn from the past couple of weeks. All I am looking for a developer focused blog post. 
- [x] to turn this in, submit to me, via the github issue, the link to the blog post

### Adventure Mode

- [ ] As we progress, we will be using different tools to work our brain. Today, head over to hackerrank.com (https://www.hackerrank.com/). This is another tool, like codewars to practice our developer skills. As a start, head into the algorithms section, and try this one: https://www.hackerrank.com/challenges/grading/problem. 
- [ ] To turn this, create a gist (gist.github.com) of your code and put it on this issue

### Epic Mode

- [ ] Go back and finish up any oustanding work. 
- [ ] Go back to an old assignment and work on it some more. This could trying to tackle a harder level. Or going back and working on the UI/UX of an assignment, refactor the code to a new idea that we covered (EX: functions and abstractions) or adding unit tests to a something 
- [ ] to turn this, put the github repo here, and tell me about what you did.

## Info on the Hack-a-thon
You can find info on the hackathon at: http://synapsefl.com/innovationsummit2018/challenges/hackathons/

They should register at https://docs.google.com/forms/d/e/1FAIpQLSdNOVNIRIkRzUODo4bEt-UU_yLgNq9mTt51z-Mb5aSpQ-wqag/viewform

The livestream will be on this facebook page: https://www.facebook.com/events/227298157831280

The address for tonight’s Info Session is below.

Please park in the lot across Palm Avenue from the ECC.

Entrepreneur Collaborative Center
2101 E Palm Ave, Tampa, FL 33605

Immediately following the information session the challenges will be published in a Google Drive folder on synapsesummit.com/hackathons

Join the Suncoast Developers Guild Slack Channel and use the #innovationsummithack channel to ask questions, collaborate, find a team, and get updates! Be on the lookout for check-ins from the organizers. :slightly_smiling_face:

Link to join:

https://join.slack.com/t/suncoast-devs/shared_invite/enQtMzE1NzYyNjM3NzE1LTUwYmJiZmQwNzMwOTJlMTczMzQ4ODdiYmE5NDJiMDgwOGY2ODRmNDIxNTIzMGQ1ZmI3OTEwYmVjZmU3YzYzZjY

Let us know if you have any questions.

**Comment by floh1695** [comment]
https://medium.com/@charlesbayley/re-implementation-of-array-higher-order-functions-in-javascript-e0768d668872

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/l1J9FCfLyq6k6tSzS/200w_d.gif)

**Comment by mdewey** [comment]
![Awesome Work!](https://media1.giphy.com/media/l1J9FCfLyq6k6tSzS/200w_d.gif)
